---
swagger: "2.0"
info:
  version: "2018-01-24T05:09:17Z"
  title: "HotWaterAPI"
host: "--yourapihostname--"
basePath: "/prod"
schemes:
- "https"
paths:
  /HotWater_Update:
    post:
      produces:
      - "application/json"
      responses: {}
      x-amazon-apigateway-integration:
        responses:
          default:
            statusCode: "200"
        uri: "arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:--yourid--:function:HotWater_Update/invocations"
        passthroughBehavior: "when_no_match"
        httpMethod: "POST"
        contentHandling: "CONVERT_TO_TEXT"
        type: "aws_proxy"
